drop table restaurants if exists;
drop table reviews if exists;
drop table users if exists;

create table restaurants (
    id bigint generated by default as identity,
    address varchar(255),
    email varchar(255),
    logo varchar(255),
    name varchar(255),
    phone varchar(255),
    url varchar(255),
    primary key (id)
);
create table reviews (
    id bigint generated by default as identity,
    date_created timestamp not null,
    rating integer,
    text varchar(255),
    restaurant_id bigint,
    user_id bigint,
    primary key (id)
);
create table users (
    id bigint generated by default as identity,
    email varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255),
    primary key (id)
);
alter table reviews
    add constraint FKsu8ow2q842enesfbqphjrfi5g
    foreign key (restaurant_id)
    references restaurants;
alter table reviews
    add constraint FKcgy7qjc1r99dp117y9en6lxye
    foreign key (user_id)
    references users;
