Hibernate: 
    drop table restaurants if exists
Hibernate: 
    drop table restaurants_reviews if exists
Hibernate: 
    drop table reviews if exists
Hibernate: 
    drop table users if exists
Hibernate: 
    create table restaurants (
        id bigint generated by default as identity,
        address varchar(255),
        email varchar(255),
        logo varchar(255),
        name varchar(255),
        phone varchar(255),
        url varchar(255),
        primary key (id)
    )
Hibernate: 
    create table restaurants_reviews (
        restaurant_id bigint not null,
        reviews_id bigint not null
    )
Hibernate: 
    create table reviews (
        id bigint not null,
        date_created timestamp not null,
        rating integer,
        text varchar(255),
        user_id bigint,
        primary key (id)
    )
Hibernate: 
    create table users (
        id bigint generated by default as identity,
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        primary key (id)
    )
Hibernate: 
    alter table restaurants_reviews 
        add constraint UK_7yyw4oyjcl4mggnlv937b8dby unique (reviews_id)